UPDATE permissions SET description = 'Permite acceder y visualizar el cotizador publico o interno' WHERE code = 'quoter:view';
UPDATE permissions SET description = 'Permite administrar opciones, precios y parametros del cotizador' WHERE code = 'quoter:manage';
UPDATE permissions SET description = 'Permite ver las metricas y el resumen general del panel de control' WHERE code = 'admin.dashboard.view';
UPDATE permissions SET description = 'Permite ver el directorio y los detalles de los contactos o clientes' WHERE code = 'admin.contactos.view';
UPDATE permissions SET description = 'Permite crear, editar y eliminar informacion de contactos' WHERE code = 'admin.contactos.manage';
UPDATE permissions SET description = 'Permite asignar ejecutivos o responsables a los contactos' WHERE code = 'admin.contactos.assign';
UPDATE permissions SET description = 'Permite leer el libro de reclamaciones y quejas registradas' WHERE code = 'admin.reclamos.view';
UPDATE permissions SET description = 'Permite gestionar, responder y cerrar reclamos' WHERE code = 'admin.reclamos.manage';
UPDATE permissions SET description = 'Permite visualizar el historial de cotizaciones generadas' WHERE code = 'admin.cotizador.view';
UPDATE permissions SET description = 'Permite crear, modificar y eliminar cotizaciones' WHERE code = 'admin.cotizador.manage';
UPDATE permissions SET description = 'Permite ver la lista de proyectos del portafolio publico' WHERE code = 'admin.portafolio.view';
UPDATE permissions SET description = 'Permite gestionar los items visibles en el portafolio publico' WHERE code = 'admin.portafolio.manage';
UPDATE permissions SET description = 'Permite ver la lista de usuarios administradores y del equipo' WHERE code = 'admin.usuarios.view';
UPDATE permissions SET description = 'Permite invitar, editar y suspender usuarios del sistema' WHERE code = 'admin.usuarios.manage';
UPDATE permissions SET description = 'Permite visualizar los roles y los permisos asociados' WHERE code = 'admin.roles.view';
UPDATE permissions SET description = 'Permite crear y modificar roles y permisos de acceso' WHERE code = 'admin.roles.manage';
UPDATE permissions SET description = 'Permite ver el contenido gestionable del sitio (blogs, paginas)' WHERE code = 'admin.cms.view';
UPDATE permissions SET description = 'Permite crear, publicar y editar contenido del sitio (CMS)' WHERE code = 'admin.cms.manage';
UPDATE permissions SET description = 'Permite ver el registro de actividad y logs del sistema' WHERE code = 'admin.auditoria.view';
UPDATE permissions SET description = 'Permite ver la configuracion de seguridad y escaneos' WHERE code = 'admin.seguridad.view';
UPDATE permissions SET description = 'Permite aplicar parches y ajustar reglas de seguridad' WHERE code = 'admin.seguridad.manage';
UPDATE permissions SET description = 'Permite ver los ajustes generales del sistema' WHERE code = 'admin.configuracion.view';
UPDATE permissions SET description = 'Permite modificar ajustes criticos y parametros globales' WHERE code = 'admin.configuracion.manage';
