name: Ephemeral Environments

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  manage_env:
    runs-on: ubuntu-latest
    steps:
      - name: Manage Ephemeral Environment via SSH
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.VPS_HOST }}
          username: githubdeploy
          key: ${{ secrets.VPS_SSH_KEY }}
          port: 22
          script: |
            /var/www/deploy-ephemeral.sh ${{ github.event.action }} ${{ github.event.number }} ${{ github.event.pull_request.head.ref }}
