name: Ephemeral Environments

on:
  pull_request:
    types: [opened, synchronize, closed]

jobs:
  manage_env:
    runs-on: self-hosted
    steps:
      - name: Manage Ephemeral Environment
        run: |
          /var/www/deploy-ephemeral.sh ${{ github.event.action }} ${{ github.event.number }} ${{ github.event.pull_request.head.ref }}
